graph [
  directed 1
  node [
    id 0
    label "android.widget.Button"
    type "class"
    comment "&#10; * A user interface element the user can tap or click to perform an action.&#10; *&#10; * <p>To display a button in an activity, add a button to the activity's layout XML file:</p>&#10; *&#10; * <pre>&#10; * &#38;lt;Button&#10; *     android:id=&#34;@+id/button_id&#34;&#10; *     android:layout_height=&#34;wrap_content&#34;&#10; *     android:layout_width=&#34;wrap_content&#34;&#10; *     android:text=&#34;@string/self_destruct&#34; /&#38;gt;</pre>&#10; *&#10; * <p>To specify an action when the button is pressed, set a click&#10; * listener on the button object in the corresponding activity code:</p>&#10; *&#10; * <pre>&#10; * public class MyActivity extends Activity {&#10; *     protected void onCreate(Bundle savedInstanceState) {&#10; *         super.onCreate(savedInstanceState);&#10; *&#10; *         setContentView(R.layout.content_layout_id);&#10; *&#10; *         final Button button = findViewById(R.id.button_id);&#10; *         button.setOnClickListener(new View.OnClickListener() {&#10; *             public void onClick(View v) {&#10; *                 // Code here executes on main thread after user presses button&#10; *             }&#10; *         });&#10; *     }&#10; * }</pre>&#10; *&#10; * <p>The above snippet creates an instance of {@link android.view.View.OnClickListener} and wires&#10; * the listener to the button using&#10; * {@link #setOnClickListener setOnClickListener(View.OnClickListener)}.&#10; * As a result, the system executes the code you write in {@code onClick(View)} after the&#10; * user presses the button.</p>&#10; *&#10; * <p class=&#34;note&#34;>The system executes the code in {@code onClick} on the&#10; * <a href=&#34;{@docRoot}guide/components/processes-and-threads.html#Threads&#34;>main thread</a>.&#10; * This means your onClick code must execute quickly to avoid delaying your app's response&#10; * to further user actions.  See&#10; * <a href=&#34;{@docRoot}training/articles/perf-anr.html&#34;>Keeping Your App Responsive</a>&#10; * for more details.</p>&#10; *&#10; * <p>Every button is styled using the system's default button background, which is often&#10; * different from one version of the platform to another. If you are not satisfied with the&#10; * default button style, you can customize it. For more details and code samples, see the&#10; * <a href=&#34;{@docRoot}guide/topics/ui/controls/button.html#Style&#34;>Styling Your Button</a>&#10; * guide.</p>&#10; *&#10; * <p>For all XML style attributes available on Button see&#10; * {@link android.R.styleable#Button Button Attributes},&#10; * {@link android.R.styleable#TextView TextView Attributes},&#10; * {@link android.R.styleable#View View Attributes}.  See the&#10; * <a href=&#34;{@docRoot}guide/topics/ui/themes.html#ApplyingStyles&#34;>Styles and Themes</a>&#10; * guide to learn how to implement and organize overrides to style-related attributes.</p>&#10; "
  ]
]
